#!/bin/sh

if [ x"${CC}" = x ]
then
  CC=gcc
fi

cd include
rm -f libstalin.a
${CC} -c -O2 -fomit-frame-pointer -freg-struct-return xlib-c.c
${CC} -c -O2 -fomit-frame-pointer -freg-struct-return gl-c.c
ar rc libstalin.a xlib-c.o gl-c.c
case `uname -s`/`uname -r` in
  IRIX*/*)   RANLIB=touch;;
  SunOS/5.*) RANLIB=touch;;
  *)         RANLIB=ranlib;;
  esac
$RANLIB libstalin.a
rm xlib-c.o gl-c.o
